spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  redis:
    cache:
      type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: user-api
  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: DEBUG
    com.payment.userapi: DEBUG

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: user-api
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO
    com.payment.userapi: INFO

server:
  port: 8081