spring:
  application:
    name: payment-api
  jmx:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:dongmin;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        #show_sql: true
        format_sql: true

payment:
  toss:
    client_api_key: client_api_key
    secret_api_key: secret_api_key
    success_url: "http://localhost:8080/api/v1/payments/toss/success"
    fail_url : "http://localhost:8080/api/v1/payments/toss/fail"

logging:
    level:
        root: DEBUG

snowflake:
    worker-id: 0
    datacenter-id: 0
