spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: payment-api
  jmx:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:dongmin;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

payment:
  toss:
    client_api_key: client_api_key
    secret_api_key: secret_api_key
    success_url: "http://localhost:8080/api/v1/payments/toss/success"
    fail_url: "http://localhost:8080/api/v1/payments/toss/fail"

logging:
  level:
    root: DEBUG

snowflake:
  worker-id: 0
  datacenter-id: 0

---
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: payment-api
  jmx:
    enabled: false
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate  # 프로덕션에서는 validate 사용
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect

payment:
  toss:
    client_api_key: ${TOSS_CLIENT_API_KEY}
    secret_api_key: ${TOSS_SECRET_API_KEY}
    success_url: "http://${EC2_PUBLIC_IP}:8080/api/v1/payments/toss/success"
    fail_url: "http://${EC2_PUBLIC_IP}:8080/api/v1/payments/toss/fail"

logging:
  level:
    root: INFO
    com.your.package: DEBUG

snowflake:
  worker-id: 0
  datacenter-id: 0
