###
# @no-redirect
POST localhost:8080/api/v1/member/signup
Content-Type: application/json

{
  "name": "장동민",
  "email": "jangdm37@gmail.com",
  "password": "1234",
  "phoneNumber": "010-1234-5678"
}

###
POST localhost:8080/api/v1/member/signIn
Content-Type: application/json

{
  "email": "jangdm37@gmail.com",
  "password2": "1234"
}

###
GET localhost:8080/api/v1/payments/history?email=user@example.com

###
POST localhost:8080/api/v1/payments/toss
Content-Type: application/json

