spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: payment-api
  datasource:
    url: jdbc:h2:mem:paymentdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

payment:
  toss:
    client_api_key: client_api_key
    secret_api_key: secret_api_key
    success_url: "http://localhost:8080/api/v1/payments/toss/success"
    fail_url: "http://localhost:8080/api/v1/payments/toss/fail"

logging:
  level:
    root: DEBUG
    com.payment.paymentapi: DEBUG

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: payment-api
  datasource:
    url: ${PAYMENT_DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

payment:
  toss:
    client_api_key: ${TOSS_CLIENT_API_KEY}
    secret_api_key: ${TOSS_SECRET_API_KEY}
    success_url: "http://${EC2_PUBLIC_IP}:8080/api/v1/payments/toss/success"
    fail_url: "http://${EC2_PUBLIC_IP}:8080/api/v1/payments/toss/fail"

logging:
  level:
    root: INFO
    com.payment.paymentapi: INFO

server:
  port: 8080