spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
server:
  servlet:
    session:
      cookie:
        domain: localhost
        path: /
        name: JSESSIONID
rest:
  template:
    clients:
      tossPayments:
        connect-timeout: 5000  # 5초
        read-timeout: 15000    # 15초
      anotherClient:
        connect-timeout: 3000
        read-timeout: 3000
cache:
  ttl: 3600  # 1시간
  eviction-strategy: allkeys-lru

---
spring:
  h2:
    console:
      enabled: true
  config:
    activate:
      on-profile: dev
  application:
    name: payment-api
  datasource:
    master:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
    slave:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

payment:
  toss:
    client_api_key: client_api_key
    secret_api_key: secret_api_key
    success_url: "http://localhost:8080/api/v1/payments/toss/success"
    fail_url: "http://localhost:8080/api/v1/payments/toss/fail"

logging:
  level:
    root: DEBUG
    com.payment.paymentapi: DEBUG

server:
  port: 8080

---
spring:
  h2:
    console:
      enabled: false
  config:
    activate:
      on-profile: prod
  application:
    name: payment-api
  datasource:
    master:
      jdbc-url: ${DATABASE_URL}
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
    slave:
      jdbc-url: ${DATABASE_SLAVE_URL}
      username: ${DATABASE_SLAVE_USERNAME}
      password: ${DATABASE_SLAVE_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 20
        minimum-idle: 10

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

payment:
  toss:
    client_api_key: ${TOSS_CLIENT_API_KEY}
    secret_api_key: ${TOSS_SECRET_API_KEY}
    success_url: "http://${EC2_PUBLIC_IP}:8080/api/v1/payments/toss/success"
    fail_url: "http://${EC2_PUBLIC_IP}:8080/api/v1/payments/toss/fail"

logging:
  level:
    root: INFO
    com.payment.paymentapi: DEBUG
    com.zaxxer.hikari: DEBUG

server:
  port: 8080