name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Copy files to S3 with AWS CLI
        run: |
          aws deploy push \
            --application-name code-deploy2 \
            --s3-location s3://cicd-s3-payment/app.zip \
            --source .
      - name: Deploy to EC2 from S3
        run: |
          aws deploy create-deployment \
            --application-name code-deploy2 \
            --deployment-group-name code-deploy2-group \
            --s3-location bucket=cicd-s3-payment,key=app.zip,bundleType=zip