name: Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # v3로 업데이트

      - name: Set up JDK 21
        uses: actions/setup-java@v3  # v3로 업데이트
        with:
          java-version: '21'
          distribution: 'temurin'  # AdoptOpenJDK가 Temurin으로 변경됨

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2  # Gradle 캐싱을 위한 액션 추가

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -i private_key -o StrictHostKeyChecking=no build/libs/*.jar ${USER}@${HOST}:~/app/
          ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
            cd ~/app && ./deploy.sh
          '