name: Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          # SSH 키 설정
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          
          # JAR 파일 전송
          scp -i private_key -o StrictHostKeyChecking=no build/libs/payment-api-0.0.1-SNAPSHOT.jar ${USER}@${HOST}:~/app/
          if [ $? -ne 0 ]; then
            echo "Failed to copy JAR file"
            exit 1
          fi
          
          # 배포 스크립트 실행
          ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
            cd ~/app
            ./deploy.sh
          '
          if [ $? -ne 0 ]; then
            echo "Deployment script failed"
            exit 1
          fi
          
          echo "Deployment completed successfully"